### ISSUE TITLE
Add sample information in the Services pages

### ISSUE THREAD

**Issue by Petrosdevri** [bitdexv/bit-developers#5]
I believe we need to add some sample information in the Services pages so that their content page doesn't look empty. I can start with the first 3 (Website Development, e-Commerce Development, and SEO / Analytics).

**Comment by bitdexv** [comment]
> I believe we need to add some sample information in the Services pages so that their content page doesn't look empty. I can start with the first 3 (Website Development, e-Commerce Development, and SEO / Analytics).

okk.. go ahead,  assigning this to you...
Add 3 more headings like "Community Collaboration" and "Tech Trends & Insights" with description.
